list = [
     'hei ' , 'liker du snakke om din selv ?' , 'når du stå opp ?', 'kan du snakke om live ditt ?',
         'når du liker å kjøpe mat ?', 'er du tenker veldig mye om live og dagen ditt ?', 
         'tenker du på familien din ?' ,
        'savner du gamle live ditt ?' , 'hva du vil jobe i framtid ?'  ,'hva heter du ?' ,
          'hvor kommer du fra ?' , 'Er du ny her ?' ,
       'hvor bor du ?' , 'hvor jobber du ? ' ,
        'hva gjør du ? ' , 'hva er morsmålet ditt ? ' , 'snakker du norsk ? ',
          'går du på norskkurs ?' 
        ,
        'hvordan går det på norskkurset ?' , 'hvilke dager går du på norskkurs ? ' ,
          'når begynner norskkurset ? ' ,
          'når slutten norskkurset ?' , 
        'hva skal du  gjør  i helga ? ' , 'hvordan går det ?' , 'har du familie ?' , 
        'hvor mange barn har du ? ' ,'hvor gamle er du ?' , 
        'er du gift ?' , 'hvor gamle er barna dine ? ' ,'hva liker du å spille ?' ,
          'Hva ser du på tv ?' 
        , 
        'liker du skolen ?' , 'har du en kjæreste ?' , 'Hva ønsker du å få jobb ?' ,'Har du talent ?' ,
        'Skriv til meg hva du gjør når du våkner om morgenen ?' ,'Hvordan går du til jobb ?' ,
        'Bor du alene eller med familien din ?' ,
        'Vet du hvordan  lager mat ?, hva liker du å spise ? ' ,'Liker du å gå ute ?' ,
        'Hva gjør du om sommeren ?' ,
        'Jeg er trist kan du lage meg å le ?' , 'hva du gjøre på framtid ?',
        'går du på gym eller skole ?',
        'liker du å gjøpe klær ?',
        'hvilken type klær du liker ?','når du født ?','når har du borsdag ?','liker du går på tur ?',
        'hvilen tur masse du liker ?',
        'hva er din favoritt sport ?','hva er din favoritt hobbi ?','hvem er bedre cr7 eller messi ?',
        'hvor du vil reise etter job ?',
        'hvilken land du vil dra på ferie ?','hva skal du gjøre i live ditt ?',
        'er du klar å starte ny live ?',
        'jeg vet ikke hvis du har motivison ?',
        'hva synes du om dem ?','hva du lært fra live ditt ?',
        'hvem er fortelle deg om din job ?','er du klar å starte ny live ?',
        'hva du skal gjøre når opphold kommer til deg ?',
        'var du på norskkurs før ?','hvor lenge du går på skole ?','liker du gamle mennsker ?',
        'hva du gjøre på kroppen din hvis du er lege ?','hvor mange gang du besøke legen ?',
        'liker du å sjekke på helsen din ?',
        'liker du å ser på nyheter ?','hvilken kanalle du liker ?',
        'er du morsomt person eller du liker ikke bli sånn ?',
        'har du lyst å har venner ?','når du gift ? ','er det bra du dele din job med folkens ?',
        'hva du tror om mennesker ?',
        'hvor masse språk du klar ?','hva er din spesial språk ?','hva telefon du liker ?',
        'hvilken folkens liker mest iphone eller samsung ?','liker du å går på kino ?',
        'hvilken filmen du liker ?',
        'liker du action film eller romantik og skummel ?',
        'husker du din gamle huset ?','liker du barne filmen ?',
        'hvilken sted du tror er beste plass for live ?','hvilken kultur du liker ?',
        'hva er din kultur ?','liker du smynke ?','hvordan du bruke smynke ?',
        'hvilken farge du liker ?' ,'liker du jobe med dame eller man ?',
        'hva du liker å studere ?','er du man eller dame ?',
        'hva liker du spise ?','går du på fest ?','hva gjøre du på dagen ?',
        'hva gjøre du på middagen ?',
        'kan du kjøre bil ?','kan du maler ?','liker du leser bok ?',
        'liker du høre på musik ?','hvordan du liker å reise til andre land ?',
        'liker du reise med bussen eller tog eller fly og hvorfor ?',
        'har du barn og hvor mange gutter og jenter ?',
        'er du gift eller du har kjæreste eller ingeting ?',
    
    

]